export const ME_GET = 'ME_GET'
export const ME_LOGIN = 'ME_LOGIN'
export const ME_RESET = 'ME_RESET'
export const ME_ERROR = 'ME_ERROR'

export const PRODUCT_GET = 'PRODUCT_GET'
export const PRODUCT_ALL = 'PRODUCT_ALL'
export const PRODUCT_CREATE = 'PRODUCT_CREATE'
export const PRODUCT_EDIT = 'PRODUCT_EDIT'
export const PRODUCT_ERROR = 'PRODUCT_ERROR'
export const PRODUCT_DELETE = 'PRODUCT_DELETE'
